version: '3.8'
services:
  multi-agent:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - CREWAI_VERBOSE=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./logs:/app/logs
      - ./multi_agent_system:/app/multi_agent_system
    restart: unless-stopped
