name: Basic CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    
    - name: Test basic functionality
      run: |
        echo "Testing basic functionality..."
        python --version
        echo "Python is working!"
        
        # Test file structure
        ls -la
        echo "Files are present!"
        
        # Test basic Python
        python -c "print('Hello from CI!')"
        python -c "import sys; print(f'Python version: {sys.version}')"
        
        echo "All basic tests passed! ✅"
