name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r multi_agent_system/requirements.txt
    
    - name: Run basic tests
      env:
        OPENAI_API_KEY: test-key-for-ci
      run: |
        cd tests
        python -m pytest test_basic.py -v
    
    - name: Check Python syntax
      run: |
        python -m py_compile multi_agent_system/api/main.py
        python -m py_compile multi_agent_system/core/config.py
        python -m py_compile multi_agent_system/core/orchestrator.py
